import { Container, Typography } from "@mui/material";
import Head from "next/head";
// import Image from "next/image";
// import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <Container maxWidth={false}>
      <Head>
        <title>Clickup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Typography variant="h1" textAlign={"center"}>
        Clickup
      </Typography>
    </Container>
  );
}
